name: Auto Daily Update

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file and README
        run: |
          TIMESTAMP=$(date +'%Y-%m-%d %H:%M:%S')
          echo "Terakhir diperbarui pada: $TIMESTAMP" > update.txt
          
          sed -i '/<!-- update-start -->/,/<!-- update-end -->/c\<!-- update-start -->\nLast Update: '"$TIMESTAMP"'\n<!-- update-end -->' README.md

      - name: Commit and Push
        run: |
          git config --global user.name "flessan"
          git config --global user.email "thiosaputra605@gmail.com"
          
          git add update.txt README.md
          git commit -m "chore: auto update tanggal $(date +'%Y-%m-%d')" || exit 0
          git push
