name: Auto Daily Update

on:
  schedule:
    # Berjalan otomatis setiap hari jam 00:00 UTC (07:00 WIB)
    - cron: '0 0 * * *'
  workflow_dispatch: # Memunculkan tombol "Run workflow" untuk tes manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update file with current date
        run: |
          echo "Terakhir diperbarui pada: $(date)" > update.txt

      - name: Commit and Push
        run: |
          git config --global user.name "flessan"
          git config --global user.email "thiosaputra605@gmail.com"
          
          git add update.txt
          git commit -m "chore: auto update tanggal $(date +'%Y-%m-%d')" || exit 0
          git push
