name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      # Step tambahan untuk mengatur identitas pengirim
      - name: Set Git Config
        run: |
          git config --global user.name "Thio Saputra"
          git config --global user.email "thiosaputra605@gmail.com"

      - uses: lowlighter/metrics@latest
        with:
          user: flessan
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "update metrics for Thio Saputra"
          
          # Plugins
          plugin_isocalendar: yes
