name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tetap pakai username untuk akses data
          user: flessan
          
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Kamu bisa tulis nama kamu di pesan commit-nya
          committer_message: "update metrics for Thio Saputra (flessan)"
          
          # Plugins
          plugin_isocalendar: yes
