name: Metrics
on:
  # Schedule updates
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Menentukan target akun yang akan diambil datanya
          user: flessan
          
          # Token utama (pastikan secrets.METRICS_TOKEN punya akses ke akun flessan)
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Konfigurasi agar commit hasil metrics menggunakan identitas email kamu
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_github: thiosaputra605@gmail.com
          
          # Plugins
          plugin_isocalendar: yes
